import unittest
import numpy as np
from python.utils import parse_pig_file, sort_notes_by_time
import os

class TestParsingAndSorting(unittest.TestCase):

    def test_sorting_logic_against_cpp_ground_truth(self):
        """
        Verifies that the Python parsing and sorting logic produces a pitch
        sequence identical to the one generated by the C++ binary.
        """
        ground_truth_file = 'tests/ref_pitch_sequence_001.txt'
        self.assertTrue(os.path.exists(ground_truth_file), "Ground truth file not found. Generate it first.")

        # Step 1: Parse the score file and apply the time-dependent sorting.
        notes = parse_pig_file('scores/001-1_fingering.txt')
        sorted_notes = sort_notes_by_time(notes)

        # Step 2: Load the ground truth pitch sequence from the committed file.
        with open(ground_truth_file, 'r') as f:
            cpp_pitches = [int(line.strip()) for line in f if line.strip()]

        # Step 3: Replicate the note processing order from the C++ Viterbi function.
        py_pitch_sequence = []

        right_hand_notes = sorted_notes[sorted_notes['channel'] == 0]
        if len(right_hand_notes) > 2:
            py_pitch_sequence.extend(right_hand_notes[2:]['pitch'])

        left_hand_notes = sorted_notes[sorted_notes['channel'] == 1]
        if len(left_hand_notes) > 2:
            py_pitch_sequence.extend(left_hand_notes[2:]['pitch'])

        # Step 4: Assert that the Python-generated sequence is identical to the C++ one.
        self.assertEqual(py_pitch_sequence, cpp_pitches, "Python's sorted pitch sequence must match the C++ ground truth.")

if __name__ == '__main__':
    unittest.main()
